language: java
jdk: oraclejdk8

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - raghunatha517@gmail.com
    on_success: always
    on_failure: always
